@startuml wallet_class_diagram

!define FONTNAME "Helvetica"
!define FONTSIZE 16

scale 0.8

skinparam defaultFontName FONTNAME
skinparam defaultFontSize FONTSIZE
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho

skinparam nodesep 60
skinparam ranksep 80
skinparam padding 8
skinparam roundcorner 20
skinparam defaultTextAlignment center


abstract class WalletBase {
  +addressType: AddressType
  +derivationPath: String
  +accountIndex: int
  +descriptor: String
  +{abstract} getAddress(addressIndex: int, isChange: bool): String
  +{abstract} getAddressWithDerivationPath(derivationPath: String): String
  +{abstract} hasPublicKeyInPsbt(psbt: String): bool
  +{abstract} addSignatureToPsbt(psbt: String): String
}

abstract class MultisignatureWalletBase {
  -_requiredSignature: int
  -_keyStoreList: List<KeyStore>
  +totalSigner: int
  +requiredSignature: int
  +keyStoreList: List<KeyStore>
  +getCoordinatorBsms(): String
  +getWitnessScript(derivationPath: String): String
  +getAddregatedPublilcKey(addressIndex: int, isChange: bool, isSort: bool): String
}

abstract class SingleSignatureWalletBase {
  -_keyStore: KeyStore
  +keyStore: KeyStore
  +getPublicKey(addressIndex: int, isChange: bool): String
  +getPublicKeyWithDerivationPath(derivationPath: String): String
  +hasPublicKeyInPsbt(psbt: String): bool
}

class SingleSignatureWallet {
  +fromDescriptor(descriptor: String, ignoreChecksum: bool): SingleSignatureWallet
}

class MultisignatureWallet {
  +fromDescriptor(descriptor: String, ignoreChecksum: bool): MultisignatureWallet
  +toJson(): String
}

class SingleSignatureVault {
  +fromKeyStore(keyStore: KeyStore, addressType: AddressType, accountIndex: int): SingleSignatureVault
  +random(addressType: AddressType, mnemonicLength: int, passphrase: String, accountIndex: int): SingleSignatureVault
  +fromMnemonic(mnemonicWords: String, addressType: AddressType, passphrase: String, accountIndex: int): SingleSignatureVault
}

class MultisignatureVault {
  +fromKeyStoreList(keyStoreList: List<KeyStore>, requiredSignature: int, addressType: AddressType, accountIndex: int): MultisignatureVault
  +fromSeedList(seedList: List<Seed>, requiredSignature: int, addressType: AddressType, accountIndex: int): MultisignatureVault
  +fromCoordinatorBsms(coordinator: String, addressType: AddressType): MultisignatureVault
}

class HDWallet {
  -_d: Uint8List
  -_Q: Uint8List
  -_chainCode: Uint8List
  +depth: int
  +index: int
  +publicKey: Uint8List
  +privateKey: Uint8List
  +fingerprint: Uint8List
  +chainCode: Uint8List
  +isNeutered(): bool
  +neutered(): HDWallet
}

class Seed {
  -_entropy: String
  -_mnemonic: List<String>
  -_passphrase: String
  +mnemonic: String
  +passphrase: String
  +rootSeed: String
  +random(mnemonicLength: int, passphrase: String): Seed
  +fromHexadecimalEntropy(entropy: String, passphrase: String): Seed
  +fromBinaryEntropy(binEntropy: String, passphrase: String): Seed
}

class AddressType {
  +name: String
  +purposeIndex: int
  +prefix: String
  +scriptType: String
  +isSegwit: bool
  +isMultisignature: bool
  +isSingleSignature: bool
  +isTaproot: bool
  +getAddress(publicKey: String): String
  +getMultisignatureAddress(publicKeys: List<String>, requiredSignatures: int): String
}

class KeyStore {
  -_masterFingerprint: String
  -_hdWallet: HDWallet
  -_extendedPublicKey: ExtendedPublicKey
  -_seed: Seed
  +masterFingerprint: String
  +extendedPublicKey: ExtendedPublicKey
  +seed: Seed
  +hasSeed: bool
  +fromSeed(seed: Seed, addressType: AddressType, accountIndex: int): KeyStore
  +fromMnemonic(mnemonicWords: String, addressType: AddressType, passphrase: String, accountIndex: int): KeyStore
  +random(addressType: AddressType, mnemonicLength: int, passphrase: String, accountIndex: int): KeyStore
}

' 관계 정의
WalletBase <|-- MultisignatureWalletBase
WalletBase <|-- SingleSignatureWalletBase
MultisignatureWalletBase <|-- MultisignatureWallet
MultisignatureWalletBase <|-- MultisignatureVault
SingleSignatureWalletBase <|-- SingleSignatureVault
SingleSignatureWalletBase <|-- SingleSignatureWallet

KeyStore o-- HDWallet
KeyStore o-- ExtendedPublicKey
KeyStore o-- Seed

MultisignatureWalletBase o-- KeyStore
SingleSignatureWalletBase  o-- KeyStore

@enduml 