// Mocks generated by Mockito 5.4.4 from annotations
// in coconut_lib/test/network/node_connector_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:coconut_lib/coconut_lib.dart' as _i3;
import 'package:coconut_lib/src/network/electrum/electrum_response_types.dart'
    as _i6;
import 'package:coconut_lib/src/utils/error.dart' as _i5;
import 'package:coconut_lib/src/utils/result_type.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressBook_1 extends _i1.SmartFake implements _i3.AddressBook {
  _FakeAddressBook_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddressType_2 extends _i1.SmartFake implements _i3.AddressType {
  _FakeAddressType_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAddress_3 extends _i1.SmartFake implements _i3.Address {
  _FakeAddress_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNodeClient_4 extends _i1.SmartFake implements _i3.NodeClient {
  _FakeNodeClient_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ElectrumApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockElectrumApi extends _i1.Mock implements _i3.ElectrumApi {
  MockElectrumApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get reqId => (super.noSuchMethod(
        Invocation.getter(#reqId),
        returnValue: 0,
      ) as int);

  @override
  int get gapLimit => (super.noSuchMethod(
        Invocation.getter(#gapLimit),
        returnValue: 0,
      ) as int);

  @override
  _i4.Future<_i2.Result<String, _i5.CoconutError>> broadcast(
          String? rawTransaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcast,
          [rawTransaction],
        ),
        returnValue: _i4.Future<_i2.Result<String, _i5.CoconutError>>.value(
            _FakeResult_0<String, _i5.CoconutError>(
          this,
          Invocation.method(
            #broadcast,
            [rawTransaction],
          ),
        )),
      ) as _i4.Future<_i2.Result<String, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<_i3.WalletStatus, _i5.CoconutError>> fullSync(
          _i3.WalletBase? wallet) =>
      (super.noSuchMethod(
        Invocation.method(
          #fullSync,
          [wallet],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i3.WalletStatus, _i5.CoconutError>>.value(
                _FakeResult_0<_i3.WalletStatus, _i5.CoconutError>(
          this,
          Invocation.method(
            #fullSync,
            [wallet],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i3.WalletStatus, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<int, _i5.CoconutError>> getNetworkMinimumFeeRate() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNetworkMinimumFeeRate,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<int, _i5.CoconutError>>.value(
            _FakeResult_0<int, _i5.CoconutError>(
          this,
          Invocation.method(
            #getNetworkMinimumFeeRate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<int, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<_i3.BlockTimestamp, _i5.CoconutError>> getBlock() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlock,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i3.BlockTimestamp, _i5.CoconutError>>.value(
                _FakeResult_0<_i3.BlockTimestamp, _i5.CoconutError>(
          this,
          Invocation.method(
            #getBlock,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i3.BlockTimestamp, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<String, _i5.CoconutError>> getTransaction(
          String? txHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [txHash],
        ),
        returnValue: _i4.Future<_i2.Result<String, _i5.CoconutError>>.value(
            _FakeResult_0<String, _i5.CoconutError>(
          this,
          Invocation.method(
            #getTransaction,
            [txHash],
          ),
        )),
      ) as _i4.Future<_i2.Result<String, _i5.CoconutError>>);

  @override
  _i4.Future<void> fetchTxHistory(
    Set<_i6.GetHistoryRes>? txHistorySet,
    _i3.WalletBase? wallet,
    bool? isChange,
    Map<int, int>? maxGapMap,
    Set<int>? toFetchBlockHeightSet,
    Map<int, List<int>>? usedIndexList, {
    int? initialIndex = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTxHistory,
          [
            txHistorySet,
            wallet,
            isChange,
            maxGapMap,
            toFetchBlockHeightSet,
            usedIndexList,
          ],
          {#initialIndex: initialIndex},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [IsolateManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsolateManager extends _i1.Mock implements _i3.IsolateManager {
  MockIsolateManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize(
    _i3.NodeClientFactory? factory,
    String? host,
    int? port,
    bool? ssl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [
            factory,
            host,
            port,
            ssl,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Result<String, _i5.CoconutError>> broadcast(
          String? rawTransaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #broadcast,
          [rawTransaction],
        ),
        returnValue: _i4.Future<_i2.Result<String, _i5.CoconutError>>.value(
            _FakeResult_0<String, _i5.CoconutError>(
          this,
          Invocation.method(
            #broadcast,
            [rawTransaction],
          ),
        )),
      ) as _i4.Future<_i2.Result<String, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<_i3.WalletStatus, _i5.CoconutError>> fullSync(
          _i3.WalletBase? wallet) =>
      (super.noSuchMethod(
        Invocation.method(
          #fullSync,
          [wallet],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i3.WalletStatus, _i5.CoconutError>>.value(
                _FakeResult_0<_i3.WalletStatus, _i5.CoconutError>(
          this,
          Invocation.method(
            #fullSync,
            [wallet],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i3.WalletStatus, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<int, _i5.CoconutError>> getNetworkMinimumFeeRate() =>
      (super.noSuchMethod(
        Invocation.method(
          #getNetworkMinimumFeeRate,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<int, _i5.CoconutError>>.value(
            _FakeResult_0<int, _i5.CoconutError>(
          this,
          Invocation.method(
            #getNetworkMinimumFeeRate,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<int, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<_i3.BlockTimestamp, _i5.CoconutError>> getBlock() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBlock,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Result<_i3.BlockTimestamp, _i5.CoconutError>>.value(
                _FakeResult_0<_i3.BlockTimestamp, _i5.CoconutError>(
          this,
          Invocation.method(
            #getBlock,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i3.BlockTimestamp, _i5.CoconutError>>);

  @override
  _i4.Future<_i2.Result<String, _i5.CoconutError>> getTransaction(
          String? txHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransaction,
          [txHash],
        ),
        returnValue: _i4.Future<_i2.Result<String, _i5.CoconutError>>.value(
            _FakeResult_0<String, _i5.CoconutError>(
          this,
          Invocation.method(
            #getTransaction,
            [txHash],
          ),
        )),
      ) as _i4.Future<_i2.Result<String, _i5.CoconutError>>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WalletBase].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletBase extends _i1.Mock implements _i3.WalletBase {
  MockWalletBase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AddressBook get addressBook => (super.noSuchMethod(
        Invocation.getter(#addressBook),
        returnValue: _FakeAddressBook_1(
          this,
          Invocation.getter(#addressBook),
        ),
      ) as _i3.AddressBook);

  @override
  set addressBook(_i3.AddressBook? _addressBook) => super.noSuchMethod(
        Invocation.setter(
          #addressBook,
          _addressBook,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get identifier => (super.noSuchMethod(
        Invocation.getter(#identifier),
        returnValue: 0,
      ) as int);

  @override
  _i3.AddressType get addressType => (super.noSuchMethod(
        Invocation.getter(#addressType),
        returnValue: _FakeAddressType_2(
          this,
          Invocation.getter(#addressType),
        ),
      ) as _i3.AddressType);

  @override
  String get derivationPath => (super.noSuchMethod(
        Invocation.getter(#derivationPath),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#derivationPath),
        ),
      ) as String);

  @override
  int get accountIndex => (super.noSuchMethod(
        Invocation.getter(#accountIndex),
        returnValue: 0,
      ) as int);

  @override
  String get descriptor => (super.noSuchMethod(
        Invocation.getter(#descriptor),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.getter(#descriptor),
        ),
      ) as String);

  @override
  String getAddress(
    int? addressIndex, {
    bool? isChange = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddress,
          [addressIndex],
          {#isChange: isChange},
        ),
        returnValue: _i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAddress,
            [addressIndex],
            {#isChange: isChange},
          ),
        ),
      ) as String);

  @override
  _i3.Address getReceiveAddress() => (super.noSuchMethod(
        Invocation.method(
          #getReceiveAddress,
          [],
        ),
        returnValue: _FakeAddress_3(
          this,
          Invocation.method(
            #getReceiveAddress,
            [],
          ),
        ),
      ) as _i3.Address);

  @override
  _i3.Address getChangeAddress() => (super.noSuchMethod(
        Invocation.method(
          #getChangeAddress,
          [],
        ),
        returnValue: _FakeAddress_3(
          this,
          Invocation.method(
            #getChangeAddress,
            [],
          ),
        ),
      ) as _i3.Address);

  @override
  List<_i3.Address> getAddressList(
    int? cursor,
    int? count,
    bool? isChange,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAddressList,
          [
            cursor,
            count,
            isChange,
          ],
        ),
        returnValue: <_i3.Address>[],
      ) as List<_i3.Address>);
}

/// A class which mocks [NodeClientFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeClientFactory extends _i1.Mock implements _i3.NodeClientFactory {
  MockNodeClientFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.NodeClient> create(
    String? host,
    int? port, {
    bool? ssl = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [
            host,
            port,
          ],
          {#ssl: ssl},
        ),
        returnValue: _i4.Future<_i3.NodeClient>.value(_FakeNodeClient_4(
          this,
          Invocation.method(
            #create,
            [
              host,
              port,
            ],
            {#ssl: ssl},
          ),
        )),
      ) as _i4.Future<_i3.NodeClient>);
}
