name: 🐞 Bug Report
description: Report a bug to help us improve the project.
title: "[BUG] "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Description
        Please describe the bug clearly and concisely.

  - type: input
    id: description
    attributes:
      label: Bug Description
      description: What happened?
      placeholder: e.g. The app crashes when I click "Send"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

  - type: textarea
    id: vector
    attributes:
      label: Test Vector
      description: What are your test parameters?
      placeholder: |
        Test mnemonic: ...
        Test PSBT: ...
        Test Descriptor: ...

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: e.g. The transaction should broadcast successfully

  - type: textarea
    id: logs
    attributes:
      label: Screenshots or Logs
      description: Add any screenshots or logs that help explain the issue.


  - type: input
    id: branch
    attributes:
      label: Branch for Test
      placeholder: bug/feeRate-type-update

  - type: dropdown
    id: priority
    attributes:
      label: 🔥 Priority
      description: How urgent is this issue?
      options:
        - 🟥 Critical (blocks release)
        - 🟧 High
        - 🟨 Medium
        - 🟩 Low
      default: 2

  - type: textarea
    id: comments
    attributes:
      label: Additional Comments
      description: Add any other context or information.
      placeholder: Optional comments...
