import 'dart:math';

import 'package:coconut_lib/coconut_lib.dart';

class ContextVaultGenerator {
  static List<MultisignatureVault> vaultList = [];

  static MultisignatureVault getVaultList(int index) {
    if (vaultList.isEmpty) {
      ContextVaultGenerator();
    }
    return vaultList[index];
  }

  ContextVaultGenerator() {
    for (int i = 0; i < 1000; i++) {
      int totalSignature = Random().nextInt(10) + 1;
      int requiredSignature = Random().nextInt(totalSignature) + 1;
      List<int> contextIndexList =
          List.generate(totalSignature, (_) => Random().nextInt(300));
      List<String> contextList =
          contextIndexList.map((index) => entropy[index]).toList();
      //지갑 생성
      MultisignatureVault vault = createContextEntropyVault(
          contextList, AddressType.p2wsh,
          requiredSignature: requiredSignature);
      vaultList.add(vault);
    }
  }

  final List<String> entropy = [
    "사과",
    "바다",
    "학교",
    "바람",
    "우산",
    "고양이",
    "강아지",
    "별",
    "구름",
    "나무",
    "창문",
    "시간",
    "휴식",
    "계절",
    "여름",
    "겨울",
    "봄",
    "가을",
    "감정",
    "기억",
    "소리",
    "바위",
    "나비",
    "우주",
    "거리",
    "사랑",
    "행복",
    "고통",
    "기대",
    "자유",
    "질문",
    "대답",
    "꿈",
    "현실",
    "여행",
    "모험",
    "약속",
    "진실",
    "거짓",
    "용기",
    "배려",
    "상상",
    "감성",
    "노력",
    "기회",
    "만남",
    "이별",
    "시작",
    "끝",
    "존재",
    "의미",
    "선택",
    "변화",
    "흐름",
    "목표",
    "평화",
    "전쟁",
    "책임",
    "도전",
    "성공",
    "실패",
    "응원",
    "치유",
    "경험",
    "관찰",
    "관계",
    "이유",
    "결과",
    "인간",
    "자연",
    "기술",
    "사회",
    "문화",
    "예술",
    "과학",
    "질서",
    "혼란",
    "집중",
    "분산",
    "고요",
    "소란",
    "조화",
    "균형",
    "반복",
    "차이",
    "공감",
    "이해",
    "정의",
    "불의",
    "유산",
    "미래",
    "과거",
    "현재",
    "환경",
    "생명",
    "정신",
    "육체",
    "영혼",
    "의식",
    "무의식",
    "표현",
    "창조",
    "파괴",
    "apple",
    "river",
    "school",
    "wind",
    "umbrella",
    "cat",
    "dog",
    "star",
    "cloud",
    "tree",
    "window",
    "time",
    "rest",
    "season",
    "summer",
    "winter",
    "spring",
    "fall",
    "feeling",
    "memory",
    "sound",
    "rock",
    "butterfly",
    "universe",
    "street",
    "love",
    "joy",
    "pain",
    "hope",
    "freedom",
    "question",
    "answer",
    "dream",
    "reality",
    "journey",
    "adventure",
    "promise",
    "truth",
    "lie",
    "courage",
    "care",
    "imagination",
    "emotion",
    "effort",
    "chance",
    "meeting",
    "farewell",
    "start",
    "end",
    "existence",
    "meaning",
    "choice",
    "change",
    "flow",
    "goal",
    "peace",
    "war",
    "responsibility",
    "challenge",
    "success",
    "failure",
    "support",
    "healing",
    "experience",
    "observation",
    "relationship",
    "reason",
    "result",
    "human",
    "nature",
    "technology",
    "society",
    "culture",
    "art",
    "science",
    "order",
    "chaos",
    "focus",
    "distraction",
    "silence",
    "noise",
    "harmony",
    "balance",
    "repetition",
    "difference",
    "empathy",
    "understanding",
    "justice",
    "injustice",
    "legacy",
    "future",
    "past",
    "present",
    "environment",
    "life",
    "mind",
    "body",
    "soul",
    "consciousness",
    "unconscious",
    "expression",
    "creation",
    "destruction",
    "나는 오늘 새로운 꿈을 꾸었다.",
    "The sky is full of stars.",
    "지금 이 순간이 가장 소중해.",
    "Life is a journey, not a destination.",
    "그 사람은 아주 따뜻한 마음을 가지고 있어.",
    "Love makes everything possible.",
    "우리는 서로를 이해하려고 노력해야 해.",
    "Time heals all wounds.",
    "작은 선택이 큰 변화를 만든다.",
    "Happiness is found within.",
    "매일 조금씩 더 나아지고 있어.",
    "The wind is blowing softly.",
    "새로운 시작은 언제나 두렵지만 가치 있어.",
    "Believe in yourself and all that you are.",
    "우리는 모두 연결되어 있다.",
    "Every day is a second chance.",
    "용기는 두려움을 이겨내는 힘이야.",
    "Dreams don’t work unless you do.",
    "슬픔도 결국 지나간다.",
    "Change is the only constant.",
    "너의 진심은 반드시 전해질 거야.",
    "Failure is a step toward success.",
    "바람이 분다, 그리고 나는 걷는다.",
    "Focus on what you can control.",
    "이 세상은 아직 아름다워.",
    "Let your light shine.",
    "지금 느끼는 감정도 소중해.",
    "You are stronger than you think.",
    "마음을 열면 세상이 보인다.",
    "Stay curious and keep learning.",
    "모든 것은 연결되어 있다.",
    "The best is yet to come.",
    "오늘의 선택이 내일을 만든다.",
    "Don’t be afraid to fail.",
    "사람은 실수로 성장해.",
    "Trust the timing of your life.",
    "포기하지 마, 조금만 더 가보자.",
    "Kindness changes everything.",
    "기억은 시간을 초월해.",
    "Breathe deeply and let go.",
    "세상은 넓고 할 일은 많다.",
    "What you seek is seeking you.",
    "고요 속에 답이 있다.",
    "Keep going, even when it’s hard.",
    "두려움은 이겨내기 위해 있는 거야.",
    "Your thoughts create your reality.",
    "내면의 평화를 찾아서.",
    "Enjoy the little things.",
    "지금이야말로 시작할 때야.",
    "Take the risk or lose the chance.",
    "내일은 또 다른 기회야.",
    "Progress, not perfection.",
    "사랑은 늘 옳다.",
    "You are your only limit.",
    "모든 순간에 의미가 있다.",
    "Grow through what you go through.",
    "어제보다 오늘, 오늘보다 내일.",
    "Be the change you wish to see.",
    "길을 잃어야 새로운 길을 찾는다.",
    "You’ve got this.",
    "시간은 항상 흘러간다.",
    "Make it happen.",
    "지금 이 자리에서 시작하자.",
    "Let it be.",
    "믿는 만큼 이루어진다.",
    "One step at a time.",
    "모든 것은 지나간다.",
    "Stay positive.",
    "지금 이 순간을 살아라.",
    "The journey is the reward.",
    "감사하는 마음이 행복을 만든다.",
    "Let your heart guide you.",
    "너는 충분히 잘하고 있어.",
    "Find peace in the process.",
    "모든 답은 너 안에 있어.",
    "Keep dreaming.",
    "기다림도 과정이야.",
    "Live with intention.",
    "그 무엇도 우연은 아니야.",
    "You are enough.",
    "어둠이 있어야 별이 보인다.",
    "Embrace the unknown.",
    "지금 포기하면 모든 게 끝이야.",
    "Do it with love.",
    "희망은 어디에나 있어.",
    "Trust yourself.",
    "삶은 선택의 연속이야.",
    "Be fearless.",
    "나 자신을 믿는 것이 시작이야.",
    "Stay strong.",
    "불확실함 속에 가능성이 있다.",
    "Live fully.",
    "매 순간을 진심으로 살아라.",
    "Never stop exploring.",
    "사랑받을 자격이 있어.",
    "Take care of your mind.",
    "꿈꾸는 것을 멈추지 마.",
    "Choose joy.",
    "넌 혼자가 아니야.",
    "Be kind to yourself."
  ];

  MultisignatureVault createContextEntropyVault(
      List<String> contextList, AddressType addressType,
      {int? requiredSignature}) {
    int numberOfEntropy = contextList.length;
    requiredSignature ??= contextList.length;

    List<KeyStore> keyStoreList = [];
    for (int i = 0; i < numberOfEntropy; i++) {
      keyStoreList.add(KeyStore.fromSeed(
          Seed.fromHexadecimalEntropy(Hash.sha256(contextList[i])),
          addressType));
    }

    return MultisignatureVault.fromKeyStoreList(keyStoreList, requiredSignature,
        addressType: addressType);
  }
}
